AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS Serverless Specification for creating API gateway.

Parameters:
  S3BucketForSrc:
    Type: String
    Default: lll-consentmgt-dev-bucket
    Description: |
      The s3 bucket for consenttmgmt src code.
  S3PathForSrc:
    Type: String
    Default: functions
    Description: |
      Path of the Jar to be deployed.
  validatorName:
    Type: String
    Default: inputValidator

Resources:
  AuthToken:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: 'LLL-authToken'
      Handler: com.amazonaws.lambda.responsys.GetResponsysAuthToken::handleRequest
      Runtime: java8
      Code:
        S3Bucket: !Ref S3BucketForSrc
        S3Key:  !Sub ${S3PathForSrc}/consentmgtapi-1.0.0-jar-with-dependencies.jar
      Description: 'Responsys getAuthToken Lambda function'
      MemorySize: 512
      Timeout: 15
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          AUTH_TYPE: password
          PASSWORD: Lulu%40lem0n
          RESPONSYS_AUTH_TOKEN_ENDPOINT: https://login2.responsys.net/rest/api/v1/auth/token
          USERNAME: loyalty_API

  ConsentMgtAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: ConsentManagementAPI
      Description: 'REST API to handle consent management behaviour updated'

  ConsentMgtAPIResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: !Ref ConsentMgtAPI
        ParentId: !GetAtt ConsentMgtAPI.RootResourceId
        PathPart: 'getauthtoken'

  Method:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId: !Ref ConsentMgtAPIResource
      RestApiId: !Ref ConsentMgtAPI
      AuthorizationType: NONE
      RequestValidatorId: !Ref RequestValidator
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub
        - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Arn}/invocations
        - Arn: !GetAtt AuthToken.Arn
        IntegrationResponses:
          - StatusCode: '200'
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - ResponseModels:
            'application/json': Empty
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Content-Type: 'application/json'
          StatusCode: '200'

  RequestValidator:
    Type: AWS::ApiGateway::RequestValidator
    Properties:
      Name: !Ref validatorName
      RestApiId: !Ref ConsentMgtAPI
      ValidateRequestParameters: true
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
    - AuthToken
    - ConsentMgtAPI
    Properties:
      FunctionName: !GetAtt AuthToken.Arn
      Action: "lambda:InvokeFunction"
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub
      - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/*/GET/getauthtoken
      - __ApiId__: !Ref ConsentMgtAPI

  GetSubscriber:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: 'LLL-getSubscriber'
      Handler: com.amazonaws.lambda.responsys.GetSubscriberInfoHandler::handleRequest
      Runtime: java8
      Code:
        S3Bucket: !Ref S3BucketForSrc
        S3Key:  !Sub ${S3PathForSrc}/consentmgtapi-1.0.0-jar-with-dependencies.jar
      Description: 'Responsys add/update subscriber info Lambda function'
      MemorySize: 512
      Timeout: 15
      Role: !GetAtt LambdaExecutionRole.Arn

  ConsentMgtAPIResource2:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: !Ref ConsentMgtAPI
        ParentId: !GetAtt ConsentMgtAPI.RootResourceId
        PathPart: 'getsubsriberinfo'

  Method2:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId: !Ref ConsentMgtAPIResource2
      RestApiId: !Ref ConsentMgtAPI
      AuthorizationType: NONE
      RequestParameters:
        method.request.querystring.emailid: true
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        RequestTemplates: 
          "application/json": "{\"id\": \"$input.params('emailid')\" }"
        Uri: !Sub
        - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Arn}/invocations
        - Arn: !GetAtt GetSubscriber.Arn
        IntegrationResponses:
          - StatusCode: '200'
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - ResponseModels:
            'application/json': Empty
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Content-Type: 'application/json'
          StatusCode: '200'

  LambdaInvokePermission2:
    Type: AWS::Lambda::Permission
    DependsOn:
    - GetSubscriber
    - ConsentMgtAPI
    Properties:
      FunctionName: !GetAtt GetSubscriber.Arn
      Action: "lambda:InvokeFunction"
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub
      - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/*/GET/getsubsriberinfo
      - __ApiId__: !Ref ConsentMgtAPI

  UpdateSubscriber:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: 'LLL-updateSubscriber'
      Handler: com.amazonaws.lambda.responsys.UpdateSubscriberInfoHandler::handleRequest
      Runtime: java8
      Code:
        S3Bucket: !Ref S3BucketForSrc
        S3Key:  !Sub ${S3PathForSrc}/consentmgtapi-1.0.0-jar-with-dependencies.jar
      Description: 'Responsys add/update subscriber info Lambda function'
      MemorySize: 512
      Timeout: 15
      Role: !GetAtt LambdaExecutionRole.Arn
      
  ConsentMgtAPIResource3:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: !Ref ConsentMgtAPI
        ParentId: !GetAtt ConsentMgtAPI.RootResourceId
        PathPart: 'updatesubscriberinfo'
        
  Method3:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId: !Ref ConsentMgtAPIResource3
      RestApiId: !Ref ConsentMgtAPI
      AuthorizationType: NONE
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub
        - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Arn}/invocations
        - Arn: !GetAtt UpdateSubscriber.Arn
        IntegrationResponses:
          - StatusCode: '200'
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - ResponseModels:
            'application/json': Empty
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Content-Type: 'application/json'
          StatusCode: '200'

  LambdaInvokePermission3:
    Type: AWS::Lambda::Permission
    DependsOn:
    - UpdateSubscriber
    - ConsentMgtAPI
    Properties:
      FunctionName: !GetAtt UpdateSubscriber.Arn
      Action: "lambda:InvokeFunction"
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub
      - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/*/POST/updatesubscriberinfo
      - __ApiId__: !Ref ConsentMgtAPI

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Effect: Allow
              Action:
                - "logs:CreateLogGroup"
              Resource: "arn:aws:logs:*:*:*"
            -
              Effect: Allow
              Action:
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
              Resource: "arn:aws:logs:*:*:*"
            -
              Effect: Allow
              Action:
                - "lambda:InvokeFunction"
              Resource: "*"
Outputs:
  RootResourceId:
    Value: !GetAtt ConsentMgtAPI.RootResourceId
